Fix: relative path for notarize file
electron/notarize pull request #180
Opened 2024-02-25 11:49 UTC by panther7

original issue: #152
original PR: #154
broken PR: #169 (thanks @DanielMcAssey )

This is fixed PR, thanks fro ASAP merge (@MarshallOfSound)

2024-02-25 19:11 UTC, DanielMcAssey commented
FYI, it's not really broken as appPath requires an absolute path as mentioned in the docs you updated

2024-02-25 19:49 UTC, panther7 commented
Ok, but my (previous) PR fixing abs/rel paths.

Why this limitation (abs path), if is easy implement both paths?

2024-02-25 21:48 UTC, MarshallOfSound requested changes
Requiring absolute paths is IMO a good thing, it removes ambiguity around the "relative to what" issue.

2024-02-28 07:56 UTC, panther7 commented
But, this it works with absolute path ...and, if some want use relative path (and know about "relative to what" issue), now it will be posible.

2024-06-06 22:36 UTC, erickzhao requested changes
I'm personally a -1 on this as well because requiring an absolute path should be easy from a user perspective.

2025-02-06 19:43 UTC, closed without merging