feat: allow notarization on macOS versions down to 10.15
electron/notarize pull request #201
Opened 2024-06-06 22:15 UTC by pjaspinski

More info in the linked issue: closes #200

2024-06-06 22:35 UTC, erickzhao commented on src/types.ts
> +
nit: I think I'd prefer just merging this with the type that accepts `appPath` to avoid having too many single-use interfaces.

2024-06-06 23:36 UTC, erickzhao reviewed
@pjaspinski I also had a question since I'm not super familiar with legacy versions of macOS:

Apple's Notarization troubleshooting documentation seems to tell users to use macOS SDK 10.9 or later because Mavericks changed how codesigning works:
https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087723

Do we want to align with that 10.9 minimum in the documentation in this case as well?

2024-06-07 07:17 UTC, pjaspinski commented
@erickzhao I made a mistake - `notarytool` is supported down to macOS version 10.15 (not 10.5). So the requirement that you mentioned is always met.

2024-06-11 16:16 UTC, erickzhao requested changes
One more doc fix, but the overall concept LGTM

2024-06-11 16:16 UTC, erickzhao commented on README.md
> +Xcode 13 is available from macOS 11.3, but notarization can be performed on systems down to macOS 10.5 ([source](https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-not
```suggestion
Xcode 13 is available from macOS 11.3, but notarization can be performed on systems down to macOS 10.15
(see [TN3147](https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool#Enable-notarization-on-an-older-version-of-macOS) for more information).
```

2024-06-13 05:33 UTC, erickzhao approved these changes

2024-08-24 02:07 UTC, dsanders11 commented on src/notarytool.ts
> +  const useXcrun = typeof notarytoolPath === 'undefined';
```suggestion
  const useXcrun = notarytoolPath === undefined;
```

No need for `typeof` here, `notarytoolPath` is declared as a parameter.

2024-08-24 02:07 UTC, dsanders11 commented on src/notarytool.ts
> +  if (typeof notarytoolPath !== 'undefined') {
```suggestion
  if (notarytoolPath !== undefined) {
```

No need for `typeof` here, `notarytoolPath` is declared as a parameter.

2024-09-17 17:28 UTC, felixrieseberg commented
This is a good PR and we'll merge it in, I just want to be clear: We're _not_ supporting older versions of macOS. Using a custom notarization tool is fully unsupported.

2024-09-17 17:28 UTC, merged