refactor: remove fs-extra dependency
electron/notarize pull request #206
Opened 2024-06-28 22:08 UTC by ckerr

Bump Node.js to 14.14.0 to pick up `fs.rm()`, use it, and drop the `fs-extra` dependency.

2024-06-28 22:20 UTC, dsanders11 requested changes
This would need to be marked as a breaking change (`BREAKING CHANGE: ` in the commit body).

@electron/wg-ecosystem policy has generally been to avoid Node.js version bumps unless necessary to avoid breaking changes on packages which fragment the install base.

I'd want to look around to see if there are any other breaking changes we can make, like more coe removal as follow-up to #187, etc, if we were going to commit to the breaking change here.

Also, do we want to do a bigger jump, to Node.js 16? I think we need to look at the general ecosystem and see how much we can lift and shift with regards to Node.js version.

2024-06-28 22:24 UTC, ckerr commented
If we're going to move the ecosystem's minimum Node.js version as a whole, v16.7.0 would be nice-to-have to pick up `fs.cp()`

2024-06-28 22:27 UTC, ckerr commented
@dsanders11 I've pushed up a rebase reword that includes the `BREAKING CHANGE` text.

+1 on deferring this pending discussion on minimum Node.js version in the ecosystem

2024-06-29 08:24 UTC, MarshallOfSound commented
I've made this case before and will make it again in Ecosystem meetings. Until there is a good forcing function to push us to a higher node version I see only harm can come from bumping the min node version and fragmenting the ecosystem across major versions.

Removing a dependency as ubiquitous as `fs-extra` isn't a solid reason IMO, because we use it in _everything_ (and lots of other folks do to) it's only installed once normally anyway 🤷 I believe this is on the docket for summit to discuss anyway

2024-06-29 18:11 UTC, closed without merging